[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "PIE", # flake8-pie
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.mypy]
check_untyped_defs = true
exclude = "migrations"
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "settings.base"

[tool.djlint]
format_js = true
format_css = true
profile = "django"
max_line_length = 119
preserve_blank_lines = true
indent = 2
line_break_after_multiline_tag = false
blank_line_after_tag = "load,extends,include"
blank_line_before_tag = "load,extends,include"

[tool.djlint.css]
indent_size = 2

[tool.djlint.js]
indent_size = 2

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "settings.test"
python_files = ["test.py", "test_*.py"]
log_cli = true
log_cli_level = "INFO"
addopts = ["--nomigrations", "--log-cli-level=INFO", "--reuse-db", "--ds=settings.test"]
